use master 
USE QLHD
create database QLHD
DROP TABLE NGUOIDUNG
DROP TABLE TAIKHOAN

CREATE TABLE TAIKHOAN
(
	TENDANGNHAP VARCHAR(12) PRIMARY KEY,
	MATKHAU  VARCHAR(8),
	TENTAIKHOAN NVARCHAR(30),
	QUYEN BIT,
)
DROP TABLE TAIKHOAN

DROP TABLE HOADON
CREATE TABLE HOADON
(
	MAHOADON VARCHAR(9),
	MAHANGHOA VARCHAR(9),
	THUNGAN NVARCHAR(12),
	TENHANGHOA NVARCHAR(30),
	SOLUONG INT,
	GIAMGIA FLOAT,
	DONGIA FLOAT,
	NGAYBAN DATETIME
)


ALTER TABLE HOADON ADD PRIMARY KEY (MAHOADON)
ALTER TABLE HOADON ADD PRIMARY KEY (MAHONGHOA)



CREATE TABLE SANPHAM
(
	MASANPHAM VARCHAR(9) PRIMARY KEY,
	TENSANPHAM NVARCHAR(30),
	SOLUONG INT,
	DONGIA INT,
	NGAYBAN DATETIME
)



