/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package com.GUI;

import Assignment_model.Load;
import java.awt.Color;
import java.awt.Image;
import java.awt.Toolkit;
import java.awt.event.KeyEvent;
import java.awt.event.WindowEvent;
import static java.lang.Thread.sleep;
import java.net.URL;
import java.util.Calendar;
import java.util.GregorianCalendar;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.ImageIcon;

/**
 *
 * @author dangt
 */
public class SetPassword extends javax.swing.JFrame {

    /**
     * Creates new form Login
     */
    public boolean loading = false;
    boolean layMatKhau;

    private SetPassword() {
        //initComponents();
        throw new UnsupportedOperationException("Not supported yet."); //To change body of generated methods, choose Tools | Templates.
    }

    public void layLaiMatKhau() {
        jlbNewPassword.setForeground(new Color(57, 113, 177));
        txtOldPassword.setVisible(false);
        jlbOldPassword.setEnabled(false);
        return;
    }
    
    public void showFrame(){
        if (this.layMatKhau){
            layLaiMatKhau();
        }
    }

    public SetPassword(boolean setPass) {
        this.layMatKhau = setPass;
        initComponents();
        showFrame();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jplMain = new javax.swing.JPanel();
        jplContainer = new javax.swing.JPanel();
        jplLogin = new javax.swing.JPanel();
        lblChuChay1 = new javax.swing.JLabel();
        jlbHide = new javax.swing.JLabel();
        jlbShow = new javax.swing.JLabel();
        jlbOldPassword = new javax.swing.JLabel();
        txtOldPassword = new javax.swing.JTextField();
        jSeparator2 = new javax.swing.JSeparator();
        txtErrorUserName = new javax.swing.JLabel();
        txtNewPassword = new javax.swing.JPasswordField();
        jlbNewPassword = new javax.swing.JLabel();
        txtErrorPassWord = new javax.swing.JLabel();
        btnLogin = new javax.swing.JButton();
        jSeparator3 = new javax.swing.JSeparator();
        jplLose = new javax.swing.JPanel();
        jlbClose = new javax.swing.JLabel();
        jlbHideOld = new javax.swing.JLabel();
        jlbShowOld = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);

        jplMain.setBackground(new java.awt.Color(64, 43, 100));
        jplMain.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jplContainer.setBackground(new java.awt.Color(64, 43, 100));

        jplLogin.setBackground(new java.awt.Color(85, 65, 118));
        jplLogin.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblChuChay1.setFont(new java.awt.Font("Tahoma", 1, 36)); // NOI18N
        lblChuChay1.setForeground(new java.awt.Color(57, 113, 177));
        lblChuChay1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/library/icon/businessman.png"))); // NOI18N
        lblChuChay1.setText("Lấy lại mật khẩu");
        jplLogin.add(lblChuChay1, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 60, 380, -1));

        jlbHide.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/library/icon/hide.png"))); // NOI18N
        jlbHide.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jlbHideMouseClicked(evt);
            }
        });
        jplLogin.add(jlbHide, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 340, -1, -1));

        jlbShow.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/library/icon/show.png"))); // NOI18N
        jlbShow.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jlbShowMouseClicked(evt);
            }
        });
        jplLogin.add(jlbShow, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 340, -1, -1));

        jlbOldPassword.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jlbOldPassword.setForeground(new java.awt.Color(57, 113, 177));
        jlbOldPassword.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/library/icon/id-card.png"))); // NOI18N
        jlbOldPassword.setText("Mật khẩu cũ");
        jlbOldPassword.addComponentListener(new java.awt.event.ComponentAdapter() {
            public void componentMoved(java.awt.event.ComponentEvent evt) {
                jlbOldPasswordComponentMoved(evt);
            }
        });
        jplLogin.add(jlbOldPassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 170, 220, 40));

        txtOldPassword.setBackground(new java.awt.Color(85, 65, 118));
        txtOldPassword.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txtOldPassword.setForeground(new java.awt.Color(255, 255, 255));
        txtOldPassword.setBorder(null);
        txtOldPassword.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                txtOldPasswordFocusGained(evt);
            }
        });
        txtOldPassword.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtOldPasswordMouseClicked(evt);
            }
        });
        txtOldPassword.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtOldPasswordActionPerformed(evt);
            }
        });
        txtOldPassword.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtOldPasswordKeyPressed(evt);
            }
        });
        jplLogin.add(txtOldPassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 220, 310, 30));
        jplLogin.add(jSeparator2, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 370, 340, 10));

        txtErrorUserName.setFont(new java.awt.Font("Segoe UI Semilight", 0, 12)); // NOI18N
        txtErrorUserName.setForeground(new java.awt.Color(255, 0, 0));
        txtErrorUserName.setText("Không hợp lệ");
        jplLogin.add(txtErrorUserName, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 260, 180, 17));

        txtNewPassword.setBackground(new java.awt.Color(85, 65, 118));
        txtNewPassword.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        txtNewPassword.setForeground(new java.awt.Color(255, 255, 255));
        txtNewPassword.setBorder(null);
        txtNewPassword.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                txtNewPasswordMouseClicked(evt);
            }
        });
        txtNewPassword.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtNewPasswordActionPerformed(evt);
            }
        });
        txtNewPassword.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyPressed(java.awt.event.KeyEvent evt) {
                txtNewPasswordKeyPressed(evt);
            }
        });
        jplLogin.add(txtNewPassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 340, 310, 30));

        jlbNewPassword.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jlbNewPassword.setForeground(new java.awt.Color(102, 102, 102));
        jlbNewPassword.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/library/icon/password.png"))); // NOI18N
        jlbNewPassword.setText("Mật khẩu mới");
        jplLogin.add(jlbNewPassword, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 290, 180, 30));

        txtErrorPassWord.setFont(new java.awt.Font("Segoe UI Semilight", 0, 12)); // NOI18N
        txtErrorPassWord.setForeground(new java.awt.Color(255, 0, 0));
        txtErrorPassWord.setText("Không hợp lệ");
        jplLogin.add(txtErrorPassWord, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 380, 180, 17));

        btnLogin.setBackground(new java.awt.Color(126, 87, 194));
        btnLogin.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        btnLogin.setForeground(new java.awt.Color(255, 255, 255));
        btnLogin.setText("Lấy lại mật khẩu");
        btnLogin.setBorder(javax.swing.BorderFactory.createEmptyBorder(1, 1, 1, 1));
        btnLogin.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLoginActionPerformed(evt);
            }
        });
        jplLogin.add(btnLogin, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 430, 340, 30));
        jplLogin.add(jSeparator3, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 250, 340, 10));

        jplLose.setBackground(new java.awt.Color(64, 43, 100));
        jplLose.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jplLoseMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jplLoseMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jplLoseMouseExited(evt);
            }
        });
        jplLose.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jlbClose.setFont(new java.awt.Font("Segoe UI Semilight", 0, 18)); // NOI18N
        jlbClose.setForeground(new java.awt.Color(255, 255, 255));
        jlbClose.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jlbClose.setText(" X");
        jlbClose.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jlbCloseFocusGained(evt);
            }
        });
        jlbClose.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jlbCloseMouseClicked(evt);
            }
            public void mouseEntered(java.awt.event.MouseEvent evt) {
                jlbCloseMouseEntered(evt);
            }
            public void mouseExited(java.awt.event.MouseEvent evt) {
                jlbCloseMouseExited(evt);
            }
        });
        jplLose.add(jlbClose, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 60, 30));

        jplLogin.add(jplLose, new org.netbeans.lib.awtextra.AbsoluteConstraints(550, 0, -1, -1));

        jlbHideOld.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/library/icon/hide.png"))); // NOI18N
        jlbHideOld.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jlbHideOldMouseClicked(evt);
            }
        });
        jplLogin.add(jlbHideOld, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 220, -1, -1));

        jlbShowOld.setIcon(new javax.swing.ImageIcon(getClass().getResource("/com/library/icon/show.png"))); // NOI18N
        jlbShowOld.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jlbShowOldMouseClicked(evt);
            }
        });
        jplLogin.add(jlbShowOld, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 220, -1, -1));

        javax.swing.GroupLayout jplContainerLayout = new javax.swing.GroupLayout(jplContainer);
        jplContainer.setLayout(jplContainerLayout);
        jplContainerLayout.setHorizontalGroup(
            jplContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jplContainerLayout.createSequentialGroup()
                .addComponent(jplLogin, javax.swing.GroupLayout.PREFERRED_SIZE, 610, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jplContainerLayout.setVerticalGroup(
            jplContainerLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jplContainerLayout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jplLogin, javax.swing.GroupLayout.PREFERRED_SIZE, 550, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        jplMain.add(jplContainer, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 610, 550));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jplMain, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jplMain, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jplLoseMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jplLoseMouseExited
        // TODO add your handling code here:
        jplLose.setBackground(new Color(204, 204, 204));
    }//GEN-LAST:event_jplLoseMouseExited

    private void jplLoseMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jplLoseMouseEntered
        jplLose.setBackground(Color.red);
        //jlbClose.setForeground(Color.white);
    }//GEN-LAST:event_jplLoseMouseEntered

    private void jplLoseMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jplLoseMouseClicked
        System.exit(0);
    }//GEN-LAST:event_jplLoseMouseClicked

    private void jlbCloseMouseExited(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jlbCloseMouseExited
        // TODO add your handling code here:
        jplLose.setBackground(new Color(64, 43, 100));
    }//GEN-LAST:event_jlbCloseMouseExited

    private void jlbCloseMouseEntered(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jlbCloseMouseEntered
        // TODO add your handling code here:
        jplLose.setBackground(Color.red);
    }//GEN-LAST:event_jlbCloseMouseEntered

    private void jlbCloseMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jlbCloseMouseClicked
        System.exit(0);
    }//GEN-LAST:event_jlbCloseMouseClicked

    private void jlbCloseFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jlbCloseFocusGained
        //jplLose.setBackground(Color.red);
        System.exit(0);
    }//GEN-LAST:event_jlbCloseFocusGained

    private void jlbOldPasswordComponentMoved(java.awt.event.ComponentEvent evt) {//GEN-FIRST:event_jlbOldPasswordComponentMoved
        // TODO add your handling code here:
    }//GEN-LAST:event_jlbOldPasswordComponentMoved

    private void txtOldPasswordFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_txtOldPasswordFocusGained
        //jlbUsername.setForeground(Color.blue);
        //        jlbUserName.setForeground(new Color(57,113,177));
        //        jlbPassWord.setForeground(new Color(102,102,102));
    }//GEN-LAST:event_txtOldPasswordFocusGained

    private void txtOldPasswordMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtOldPasswordMouseClicked
        jlbNewPassword.setForeground(new Color(102, 102, 102));
        jlbOldPassword.setForeground(new Color(57, 113, 177));
        txtErrorUserName.setVisible(false);
    }//GEN-LAST:event_txtOldPasswordMouseClicked

    private void txtOldPasswordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtOldPasswordActionPerformed
        jlbNewPassword.setForeground(new Color(102, 102, 102));
        jlbOldPassword.setForeground(new Color(57, 113, 177));

    }//GEN-LAST:event_txtOldPasswordActionPerformed

    private void txtOldPasswordKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtOldPasswordKeyPressed
        // TODO add your handling code here:
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            jlbNewPassword.setForeground(new Color(57, 113, 177));
            jlbOldPassword.setForeground(new Color(102, 102, 102));
            txtNewPassword.requestFocus();
        }
    }//GEN-LAST:event_txtOldPasswordKeyPressed

    private void jlbHideMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jlbHideMouseClicked
        //        txtPassword.setVisible(true);
        //        jlbShowPassword.setVisible(false);
        //        //password_temp = txtPassword.getText();
        jlbHide.setVisible(false);
        txtNewPassword.requestFocus();
        //        //jlbHidePassword.setVisible(false);
        //        //jlbShowPassword.setVisible(false);
        //        txtPassword.setText(password_temp);
        jlbShow.setVisible(true);
        txtNewPassword.setEchoChar('●');
        jlbOldPassword.setForeground(new Color(102, 102, 102));
        jlbNewPassword.setForeground(new Color(57, 113, 177));
        txtErrorPassWord.setVisible(false);
    }//GEN-LAST:event_jlbHideMouseClicked

    private void jlbShowMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jlbShowMouseClicked
        txtNewPassword.setEchoChar((char) 0);
        txtNewPassword.requestFocus();
        //        password_temp = txtPassword.getText();
        //        txtPassword.setVisible(false);
        //        jlbShowPassword.setText(txtPassword.getText());
        //        jlbShowPassword.setVisible(true);
        //        txtPassword.setText("");
        jlbHide.setVisible(true);
        jlbShow.setVisible(false);
        jlbOldPassword.setForeground(new Color(102, 102, 102));
        jlbNewPassword.setForeground(new Color(57, 113, 177));
        txtErrorPassWord.setVisible(false);
        //btnAdd.doClick();
    }//GEN-LAST:event_jlbShowMouseClicked

    private void txtNewPasswordMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_txtNewPasswordMouseClicked
        // TODO add your handling code here:
        jlbOldPassword.setForeground(new Color(102, 102, 102));
        jlbNewPassword.setForeground(new Color(57, 113, 177));
        txtErrorPassWord.setVisible(false);
    }//GEN-LAST:event_txtNewPasswordMouseClicked

    private void txtNewPasswordActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNewPasswordActionPerformed

    }//GEN-LAST:event_txtNewPasswordActionPerformed

    private void txtNewPasswordKeyPressed(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtNewPasswordKeyPressed
        // TODO add your handling code here:
        if (evt.getKeyCode() == KeyEvent.VK_ENTER) {
            btnLogin.doClick();
        }
    }//GEN-LAST:event_txtNewPasswordKeyPressed

    private void btnLoginActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLoginActionPerformed
        ImageIcon icon = new ImageIcon("icon/login.png");
        if (txtNewPassword.getText().equals("")) {
            //JOptionPane.showMessageDialog(this, "Vui lòng nhập Password!");
            //txtUsername.setBackground(Color.white);
            //txtPassword.setBackground(Color.pink);
            //txtErrorPassWord.setText("Required field");
            //txtErrorUserName.setText("");
            txtErrorPassWord.setVisible(true);
            txtNewPassword.requestFocus();
        }
        if (txtOldPassword.getText().equals("")) {
            //JOptionPane.showMessageDialog(this, "Vui lòng nhập Username!");
            //txtUsername.setBackground(Color.pink);
            //txtErrorUserName.setText("Required field");
            txtErrorUserName.setVisible(true);
            txtOldPassword.requestFocus();
        } else {
            //txtErrorUserName.setText("");
            //txtErrorPassWord.setText("");
            txtErrorUserName.setVisible(false);
            txtErrorPassWord.setVisible(false);
            //txtPassword.setBackground(Color.white);
            if (txtOldPassword.getText().equals("admin") && txtNewPassword.getText().equals("123")) {
                JOptionPane.showMessageDialog(this, "Đăng nhập thành công!");
                //TaiKhoan.setVisible(true);
                //jplMain.setVisible(false);
                this.loading = true;
//                Load load=new Load();
//                this.dispose();
//                load.loading();
                this.dispose();

                //JOptionPane.showMessageDialog(this, "Đăng nhập thành công", "Login",JOptionPane.INFORMATION_MESSAGE, icon);
                //System.exit(0);
            } else {
                JOptionPane.showMessageDialog(this, "Username hoặc Password không chính xác!");
                txtOldPassword.requestFocus();
            }
        }
    }//GEN-LAST:event_btnLoginActionPerformed

    private void jlbHideOldMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jlbHideOldMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jlbHideOldMouseClicked

    private void jlbShowOldMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jlbShowOldMouseClicked
        // TODO add your handling code here:
    }//GEN-LAST:event_jlbShowOldMouseClicked

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(SetPassword.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(SetPassword.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(SetPassword.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(SetPassword.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new SetPassword().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnLogin;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeparator3;
    private javax.swing.JLabel jlbClose;
    private javax.swing.JLabel jlbHide;
    private javax.swing.JLabel jlbHideOld;
    private javax.swing.JLabel jlbNewPassword;
    private javax.swing.JLabel jlbOldPassword;
    private javax.swing.JLabel jlbShow;
    private javax.swing.JLabel jlbShowOld;
    private javax.swing.JPanel jplContainer;
    private javax.swing.JPanel jplLogin;
    private javax.swing.JPanel jplLose;
    private javax.swing.JPanel jplMain;
    private javax.swing.JLabel lblChuChay1;
    private javax.swing.JLabel txtErrorPassWord;
    private javax.swing.JLabel txtErrorUserName;
    private javax.swing.JPasswordField txtNewPassword;
    private javax.swing.JTextField txtOldPassword;
    // End of variables declaration//GEN-END:variables
}
