/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package frame;

import com.hicode.switchbutton.Event;
import java.awt.Color;
import java.awt.Graphics2D;
import java.awt.Image;
import java.awt.image.BufferedImage;
import java.io.File;
import java.io.FileNotFoundException;
import java.io.FileOutputStream;
import java.io.IOException;
import java.io.OutputStream;
import java.io.OutputStreamWriter;
import java.util.ArrayList;
import java.util.Collections;
import java.util.Comparator;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.imageio.ImageIO;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author dangt
 */
public class QuanLiNhanVien extends javax.swing.JFrame {

    /**
     * Creates new form QuanLiSinhVien
     */
    DefaultTableModel model;
    List<NhanVien> list = new ArrayList<>();
    NhanVien sv = new NhanVien();
    String hinhAnh = "";

    public QuanLiNhanVien() {
        Login login = new Login();
        login.setVisible(true);
        this.dispose();
    }
    
    public QuanLiNhanVien(int i){
        initComponents();
        cloneData();
    }

    public void choseImage() {
        JFileChooser chooser = new JFileChooser(); //System.out.println(nameImage);
        chooser.showOpenDialog(null);
        File file = chooser.getSelectedFile();
        try {
            this.hinhAnh = file.getAbsolutePath();
            Image img = ImageIO.read(file);
            lblHinhAnh.setText("");
            lblHinhAnh.setIcon(new ImageIcon(img.getScaledInstance(140, 140, 0)));
        } catch (Exception e) {
            //JOptionPane.showMessageDialog(this, "Ôi không!\nBạn vừa hủy thao tác mất rồi!");
            return;
        }
        //clone ảnh

    }

    public void cloneData() {
        list.clear();
        String temp = txtFind.getText().toLowerCase();
        for (NhanVien sv : sv.getAll()) {
            String ten = sv.getHoten().toLowerCase();
            if (ten.contains(temp)) {
                list.add(sv);
            }
        }
        loadDataTable();
    }

    public void loadDataTable() {
        model = new DefaultTableModel();
        //Tạo các cột
        model.addColumn("MSNV");
        model.addColumn("HO TEN");
        model.addColumn("QUE QUAN");
        model.addColumn("CCCD");
        model.addColumn("GIOI TINH");
        model.addColumn("SDT");
        model.addColumn("LUONG");
        //model.addColumn("HINH ANH");
        //model.addColumn("TRANG THAI");
        fillToTable();
    }

    public void fillToTable() {
        //cloneData();
        //System.out.println(listLaptop.get(0).getMaLoai());
        model.setRowCount(0);
        String gioiTinh = "Nu";
        for (NhanVien index : list) {
            if (index.isGioitinh()) {
                gioiTinh = "Nam";
            }
            model.addRow(new Object[]{index.getMsnv(), index.getHoten(), index.getQuequan(), index.getCccd(), gioiTinh, index.getSdt(), index.getLuong()});
        }
        tblList.setModel(model);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        txtMSSV = new javax.swing.JTextField();
        jLabel2 = new javax.swing.JLabel();
        txtHoTen = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        txtQueQuan = new javax.swing.JTextField();
        txtCCCD = new javax.swing.JTextField();
        lblHinhAnh = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        rdoNu = new javax.swing.JRadioButton();
        rdoNam = new javax.swing.JRadioButton();
        jLabel8 = new javax.swing.JLabel();
        txtSdt = new javax.swing.JTextField();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblList = new javax.swing.JTable();
        jLabel9 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        txtFind = new javax.swing.JTextField();
        jLabel10 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jButton4 = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        txtLuong = new javax.swing.JTextField();
        jButton5 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 0, 0));
        jLabel1.setText("Quản Lí Nhân Viên");
        jPanel1.add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 20, 270, -1));
        jPanel1.add(txtMSSV, new org.netbeans.lib.awtextra.AbsoluteConstraints(87, 102, 172, 34));

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel2.setText("MSSV");
        jPanel1.add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(23, 109, -1, -1));
        jPanel1.add(txtHoTen, new org.netbeans.lib.awtextra.AbsoluteConstraints(87, 162, 172, 34));

        jLabel3.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel3.setText("Họ tên");
        jPanel1.add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(23, 169, -1, -1));
        jPanel1.add(txtQueQuan, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 90, 172, 34));
        jPanel1.add(txtCCCD, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 230, 172, 34));

        lblHinhAnh.setBorder(javax.swing.BorderFactory.createEtchedBorder());
        lblHinhAnh.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                lblHinhAnhMouseClicked(evt);
            }
        });
        jPanel1.add(lblHinhAnh, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 20, 140, 140));

        jLabel7.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel7.setText("Quê quán");
        jPanel1.add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 100, -1, -1));

        buttonGroup1.add(rdoNu);
        rdoNu.setText("Nữ");
        jPanel1.add(rdoNu, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 240, -1, -1));

        buttonGroup1.add(rdoNam);
        rdoNam.setText("Nam");
        jPanel1.add(rdoNam, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 240, -1, -1));

        jLabel8.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel8.setText("sdt");
        jPanel1.add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 170, -1, -1));
        jPanel1.add(txtSdt, new org.netbeans.lib.awtextra.AbsoluteConstraints(400, 160, 172, 34));

        tblList.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Title 1", "Title 2", "Title 3", "Title 4"
            }
        ));
        tblList.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                tblListMouseClicked(evt);
            }
        });
        jScrollPane1.setViewportView(tblList);

        jPanel1.add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 400, 780, 120));

        jLabel9.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel9.setText("Giới tính");
        jPanel1.add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 240, -1, -1));

        jLabel6.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel6.setText("Tim theo ten");
        jPanel1.add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 360, 90, 20));

        txtFind.addCaretListener(new javax.swing.event.CaretListener() {
            public void caretUpdate(javax.swing.event.CaretEvent evt) {
                txtFindCaretUpdate(evt);
            }
        });
        jPanel1.add(txtFind, new org.netbeans.lib.awtextra.AbsoluteConstraints(210, 350, 270, 30));

        jLabel10.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel10.setText("CCCD");
        jPanel1.add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 240, -1, -1));

        jButton1.setText("Cập nhật");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 220, 140, 30));

        jButton2.setText("Xóa");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 260, 140, 30));

        jButton3.setText("Thêm");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton3, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 180, 140, 30));

        jButton4.setText("In DSNV");
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton4, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 340, 140, 30));

        jLabel4.setFont(new java.awt.Font("Tahoma", 0, 14)); // NOI18N
        jLabel4.setText("Lương");
        jPanel1.add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 300, -1, -1));
        jPanel1.add(txtLuong, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 300, 170, 30));

        jButton5.setText("Tìm kiếm");
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton5, new org.netbeans.lib.awtextra.AbsoluteConstraints(500, 350, 80, 30));

        jButton6.setText("Sắp xếp");
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton6, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 300, 140, 30));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 800, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, 526, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void tblListMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_tblListMouseClicked
        int i = tblList.getSelectedRow();
        txtMSSV.setText(list.get(i).getMsnv());
        txtCCCD.setText(list.get(i).getCccd());
        txtHoTen.setText(list.get(i).getHoten());
        txtSdt.setText(list.get(i).getSdt());
        txtQueQuan.setText(list.get(i).getQuequan());
        txtLuong.setText(String.valueOf(list.get(i).getLuong()));
        if (list.get(i).isGioitinh()) {
            rdoNam.setSelected(true);
        } else {
            rdoNu.setSelected(true);
        }
        this.hinhAnh = list.get(i).getHinhanh();
        lblHinhAnh.setIcon(new ImageIcon(this.hinhAnh));
    }//GEN-LAST:event_tblListMouseClicked

    private void txtFindCaretUpdate(javax.swing.event.CaretEvent evt) {//GEN-FIRST:event_txtFindCaretUpdate

    }//GEN-LAST:event_txtFindCaretUpdate

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        boolean gt = false;
        float luong = 0;
        try {
            luong = Float.valueOf(txtLuong.getText());
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Luong khong hop le");
            return;
        }
        System.out.println(luong);
        if (rdoNam.isSelected()) {
            gt = true;
        }
        sv.add(txtMSSV.getText(), txtHoTen.getText(), txtQueQuan.getText(), txtCCCD.getText(), gt, hinhAnh, txtSdt.getText(), luong);
        JOptionPane.showMessageDialog(this, "Them thanh cong");
        cloneData();
    }//GEN-LAST:event_jButton3ActionPerformed

    private void lblHinhAnhMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_lblHinhAnhMouseClicked
        choseImage();
    }//GEN-LAST:event_lblHinhAnhMouseClicked

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        int i = tblList.getSelectedRow();
        if (i < 0) {
            JOptionPane.showMessageDialog(this, "Vui long chon doi tuong xoa!");
            return;
        }

        int ketQua = JOptionPane.showConfirmDialog(this, "Bạn chắc chắn muốn xóa?", "Xóa Nhân viên", JOptionPane.YES_NO_OPTION);
        if (ketQua == JOptionPane.YES_OPTION) {
            try {

                String msnv = tblList.getValueAt(i, 0).toString();
                sv.delete(msnv);
                JOptionPane.showMessageDialog(this, "Xóa thành công!");
                cloneData();
                return;
            } catch (Exception e) {
                //JOptionPane.showMessageDialog(this, "Xóa không thành công!\n Vui lòng chọn tài khoản từ bảng");
            }
        }
        /* 
        String mssv = JOptionPane.showInputDialog("Vui long nhap MSNV muon xoa:");
        for (NhanVien sv : list) {
            if (sv.getMsnv().equalsIgnoreCase(mssv)) {
                sv.delete(mssv);
                JOptionPane.showMessageDialog(this, "Xoa thanh cong!");
                cloneData();
                return;
            }
        }
        JOptionPane.showMessageDialog(this, "Khong ton tai");
         */
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        int i = tblList.getSelectedRow();
        if (i < 0) {
            JOptionPane.showMessageDialog(this, "Vui long chon doi tuong cap nhat!");
            return;
        }
        boolean gt = false;
        float luong = 0;
        try {
            luong = Float.valueOf(txtLuong.getText());
        } catch (Exception e) {
            JOptionPane.showMessageDialog(this, "Luong khong hop le");
            return;
        }
        int ketQua = JOptionPane.showConfirmDialog(this, "Bạn chắc chắn muốn cập nhật?", "Cập nhật Nhân viên", JOptionPane.YES_NO_OPTION);
        if (ketQua == JOptionPane.YES_OPTION) {
            if (rdoNam.isSelected()) {
                gt = true;
            }

            for (NhanVien sv : list) {
                if (sv.getMsnv().equalsIgnoreCase(txtMSSV.getText())) {
                    sv.update(txtMSSV.getText(), txtHoTen.getText(), txtQueQuan.getText(), txtCCCD.getText(), gt, this.hinhAnh, txtSdt.getText(), luong);
                    JOptionPane.showMessageDialog(this, "Cap nhat thanh cong!");
                    cloneData();
                    return;
                }
            }
            JOptionPane.showMessageDialog(this, "Khong the cap nhat");
        }

    }//GEN-LAST:event_jButton1ActionPerformed

    public void saveFile(int index) throws FileNotFoundException, IOException {
        String gt = "Nam";
        if (!list.get(index).isGioitinh()) {
            gt = "Nữ";
        }
        String[] data = {
            /*
                String.valueOf(txtUserName.getText()),
                String.valueOf(txtPassword.getText()),
                String.valueOf(txtConfirmPassword.getText())
             */
            "\t Thông tin nhân viên: " + list.get(index).getHoten() + "\n",
            "Mã số nhân viên: " + list.get(index).getMsnv() + "\n",
            "Tên nhân viên: " + list.get(index).getHoten() + "\n",
            "số CCCD: " + list.get(index).getCccd() + "\n",
            "Quê quán: " + list.get(index).getQuequan() + "\n",
            "Số điện thoại: " + list.get(index).getSdt() + "\n",
            "Giới tính: " + gt + "\n",
            "Lương: " + list.get(index).getLuong() + "\n",
            "\n\n\n"
        };

        JFileChooser fileChooser = new JFileChooser();
        fileChooser.setDialogTitle("Chọn đường dẫn lưu văn bản!");

        int userSelection = fileChooser.showSaveDialog(this);

        if (userSelection == JFileChooser.APPROVE_OPTION) {
            File fileToSave = fileChooser.getSelectedFile();
            //WriteToFile(fileToSave.getAbsolutePath() + ".docx");

            /*  
                abcde.docx
                x : length-1
                . : length-5
             */
            String path = fileToSave.getAbsoluteFile().toString();
            String file = fileToSave.getAbsolutePath();
            if (!path.contains(".doc")) {
                file = fileToSave.getAbsolutePath() + ".doc";
            }

            OutputStream outputStream = new FileOutputStream(file);
            OutputStreamWriter outputStreamWriter = new OutputStreamWriter(outputStream);

            for (String item : data) {
                outputStreamWriter.write(item);
                // Dùng để xuống hàng
                outputStreamWriter.write("\n");
            }
            // Đây là phương thức quan trọng!
            // Nó sẽ bắt chương trình chờ ghi dữ liệu xong thì mới kết thúc chương trình.
            outputStreamWriter.flush();
            JOptionPane.showMessageDialog(this, "Đã in thông tin nhân viên vào: " + path);
        }
    }

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        int i = tblList.getSelectedRow();
        if (i < 0) {
            JOptionPane.showMessageDialog(this, "Vui long chon doi tuong cap nhat!");
            return;
        }
        try {
            saveFile(i);
        } catch (IOException ex) {
            Logger.getLogger(QuanLiNhanVien.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        cloneData();
    }//GEN-LAST:event_jButton5ActionPerformed

    public void inforPC_sortTrongLuong() {
        Comparator<NhanVien> comp = new Comparator<NhanVien>() {
            public int compare(NhanVien s1, NhanVien s2) {
                if (s1.getLuong() > s2.getLuong()) {
                    return 1;
                }
                if (s1.getLuong() < s2.getLuong()) {
                    return -1;
                }
                return 0;  //s1.diemTB = s2.diemTB

            }

        };
    }

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        Comparator<NhanVien> comp = new Comparator<NhanVien>() {
            public int compare(NhanVien s1, NhanVien s2) {
                if (s1.getLuong() > s2.getLuong()) {
                    return 1;
                }
                if (s1.getLuong() < s2.getLuong()) {
                    return -1;
                }
                return 0;  //s1.diemTB = s2.diemTB

            }

        };
        int messageType = JOptionPane.QUESTION_MESSAGE;
        String[] option = {"Tăng dần", "Giảm dần", "Thoát"};
        int code = JOptionPane.showOptionDialog(this, "Bạn muốn sắp xếp tăng hay giảm?", "Sắp xếp", 0, messageType, null, option, "");
        if (code == 0) {
            Collections.sort(list, comp);
            //sort();
            loadDataTable();

        } else if (code == 1) {
            Collections.sort(list, comp.reversed());  //giảm dần
            //sortG();
            loadDataTable();
        } else {
            return;
        }
    }//GEN-LAST:event_jButton6ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(QuanLiNhanVien.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(QuanLiNhanVien.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(QuanLiNhanVien.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(QuanLiNhanVien.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new QuanLiNhanVien().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblHinhAnh;
    private javax.swing.JRadioButton rdoNam;
    private javax.swing.JRadioButton rdoNu;
    private javax.swing.JTable tblList;
    private javax.swing.JTextField txtCCCD;
    private javax.swing.JTextField txtFind;
    private javax.swing.JTextField txtHoTen;
    private javax.swing.JTextField txtLuong;
    private javax.swing.JTextField txtMSSV;
    private javax.swing.JTextField txtQueQuan;
    private javax.swing.JTextField txtSdt;
    // End of variables declaration//GEN-END:variables
}
