CREATE DATABASE QLLT
USE QLLT
CREATE TABLE LOAI(
    MALOAI NVARCHAR(10) PRIMARY KEY NOT NULL,
    TENLOAI NVARCHAR(50) 
)
CREATE TABLE NHANHIEU(
    MAHIEU NVARCHAR(10) PRIMARY KEY NOT NULL,
    TENHIEU NVARCHAR(50)
)
CREATE TABLE LAPTOP(
    MALT NVARCHAR(10)  PRIMARY KEY NOT NULL,
    TENLT NVARCHAR(50),
    MALOAI NVARCHAR(10) REFERENCES LOAI(MALOAI),
    MAHIEU NVARCHAR(10) REFERENCES NHANHIEU(MAHIEU),
    MAU NVARCHAR(20),
    GIA FLOAT
)

insert into nhanhieu values
('01','DELL'),
('02','HP'),
('03','ASUS')

insert into LOAI values
('IPD',N'Máy tính bảng'),
('PC','Laptop')

insert into laptop values
('01','DELL GAMMING 05','PC','01',N'ĐỎ',29000000),
('02','ASUS GAMMING','PC','03',N'TRẮNG BẠC',19000000),
('03','HP LAT D09','PC','02',N'TRẮNG BẠC',15000000),
('04','DELL LATUTADE','PC','01',N'ĐEN',39000000),
('05','DELL PVH4','PC','01',N'ĐỎ ĐEN',39000000)

SELECT * FROM LAPTOP